name: Before Merge

on:
  push:
    branches: ['main']

env:
  NODE_VERSION: '24.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache npm dependencies #TODO: Is this needed with setup-node cache?
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Create a file for Clasp credentials
        id: write-clasprc
        run: echo "$CLASPRC_JSON_SECRET" >> ~/.clasprc.json
        env:
          CLASPRC_JSON_SECRET: ${{ secrets.CLASPRC_JSON }}

      - name: Clone Google Apps Script project
        run: npx nx run google-apps-script:clasp --configuration=clone
        env:
          GOOGLE_SCRIPT_PROJECT_ID: ${{ secrets.GOOGLE_SCRIPT_PROJECT_ID }}

      - name: Build root project
        run: npx nx run google-apps-script:build --verbose

      - name: Push changes to Google Apps Script
        run: npx nx run google-apps-script:clasp --configuration=push
